1. Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [4]:
import numpy as np

#1

a,b=[1,1,1],[3,3,3]

A = np.array(a)
B = np.array(b)

print(-((B-A)*(B/2)))

# Ваш код здесь


[3. 3. 3.]


2. Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [12]:
#2. Ваш код здесь
import numpy as np

chees_desk = np.zeros((8,8))

chees_desk[0, :] = [-4, -3, -2, -6, -5, -2, -3, -4]
chees_desk[1, :] = -1
chees_desk[6, :] = 1
chees_desk[7, :] = [4, 3, 2, 6, 5, 2, 3, 4]

print(chees_desk)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


3. Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [21]:
# 3. Ваш код здесь

import numpy as np

number = np.arange(2,21,2)
odd_number = number + 1
multi = number*odd_number

print(number)

print(odd_number)

print(multi)


[ 2  4  6  8 10 12 14 16 18 20]
[ 3  5  7  9 11 13 15 17 19 21]
[  6  20  42  72 110 156 210 272 342 420]


4. Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент массива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [29]:
# 4. Ваш код здесь
import numpy as np
from numpy import random

arr = np.random.uniform(0, 20, size=(4, 7))

print(arr)

print()
print()

print(np.round((arr - arr.min()) / (arr.max() - arr.min()),4))

[[19.05387223 15.10676324  6.06415404  7.7532949   5.18432902 15.80708595
  15.33750481]
 [15.5759145   0.35790939  0.07623733  8.39542918  4.40271539  9.84637939
   3.68957039]
 [17.36294916  3.51106445 18.06213187 12.52778193 18.65719297 10.28985565
  18.38666573]
 [ 0.02270277  1.2936629   4.98873125  1.64641595  3.37440155 12.24203838
   4.26802373]]


[[1.     0.7926 0.3175 0.4062 0.2712 0.8294 0.8047]
 [0.8172 0.0176 0.0028 0.4399 0.2301 0.5162 0.1927]
 [0.9111 0.1833 0.9479 0.6571 0.9792 0.5395 0.9649]
 [0.     0.0668 0.2609 0.0853 0.1761 0.6421 0.2231]]


5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [30]:
# 5. 

my_array = np.array([[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15],
                    [16,17,18,19,20],
                    [21,22,23,24,25]])

# Ваш код здесь
print(my_array[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


6. Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [33]:
# 6. Ваш код здесь
my_sin = np.sin(my_array)

summ_array = np.sum(my_sin)

print(my_sin)

print()
print()

print(round(summ_array,3))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]]


-0.058


7. Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [58]:
# 7. Ваш код здесь

from numpy import random

matrix = np.random.randint(0, 100, (4, 5))

vtoroe_sverhy = matrix[0,1]

index = np.where(matrix == vtoroe_sverhy)

print(matrix)

print()

print("Второе сверху: ", vtoroe_sverhy,"\nего индекс: ",index)


[[88 35 82 97  3]
 [ 7 92 41 11 60]
 [35 61 28 49 12]
 [52 26 73 45 14]]

Второе сверху:  35 
его индекс:  (array([0, 2]), array([1, 0]))


8. Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [71]:
# 8. Ваш код здесь

from numpy import random

ar1 = np.random.randint(0, 10, (4, 7))

ar2 = np.random.randint(0, 10, (4, 7))

ar_max = np.maximum(ar1,ar2)

ar_min = np.minimum(ar1,ar2)

ar_medium = (ar_max+ar_min)/2



print(ar1)
print()
print(ar2)
print()
print(ar_max,ar_min,ar_medium, sep='\n\n')



[[7 1 7 3 9 2 9]
 [8 9 7 9 5 8 8]
 [9 3 9 4 6 3 3]
 [2 8 5 6 5 6 7]]

[[1 4 1 0 1 5 7]
 [8 9 5 7 8 8 4]
 [0 5 6 6 2 8 3]
 [6 9 4 9 5 9 6]]

[[7 4 7 3 9 5 9]
 [8 9 7 9 8 8 8]
 [9 5 9 6 6 8 3]
 [6 9 5 9 5 9 7]]

[[1 1 1 0 1 2 7]
 [8 9 5 7 5 8 4]
 [0 3 6 4 2 3 3]
 [2 8 4 6 5 6 6]]

[[4.  2.5 4.  1.5 5.  3.5 8. ]
 [8.  9.  6.  8.  6.5 8.  6. ]
 [4.5 4.  7.5 5.  4.  5.5 3. ]
 [4.  8.5 4.5 7.5 5.  7.5 6.5]]


9. Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [3]:
#9
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third])

# Ваш код здесь
great_array_filter = great_array > 50

summ_new = np.sum(great_array[great_array_filter])

print(summ_new)

5470.0


10. Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [16]:
# 10. Ваш код здесь

x = great_array.reshape(-1)

print(x[150])

5.313292845913055


11. Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [14]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь

C = np.where(A==B)

print(C)


(array([1, 3, 5, 7]),)


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [5]:
#четный числа

import numpy as np
number = np.arange(2,21,2)
#НЕчетный числа
odd_number = number + 1
#произведение массивов
multi = number*odd_number

unity = np.stack((number,odd_number,multi), axis=1)

print(unity)

[[  2   3   6]
 [  4   5  20]
 [  6   7  42]
 [  8   9  72]
 [ 10  11 110]
 [ 12  13 156]
 [ 14  15 210]
 [ 16  17 272]
 [ 18  19 342]
 [ 20  21 420]]
